name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
      
    - name: Navigate to coffee-machine folder
      run: cd coffee-machine

    - name: Build with Maven
      working-directory: coffee-machine
      run: mvn clean install
